name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- UI & UTILS ---
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # --- AUDIO & PROCESSING ---
  record: ^6.2.0
  permission_handler: ^11.3.0
  fftea: ^1.4.0
  image: ^4.1.7

  # --- AI ENGINES ---
  pytorch_lite: ^4.3.0
  tflite_flutter: ^0.11.0
  opencv_dart: ^2.2.1+4
  face_detection_tflite: ^5.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # --- APP ICON GENERATOR ---
  flutter_launcher_icons: ^0.13.1

# --- LAUNCHER ICON CONFIG (top-level) ---
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/apk_icon.png
  min_sdk_android: 21

# --- ASSETS ---
flutter:
  uses-material-design: true
  assets:
    - assets/models/final_face_model_mobile.ptl
    - assets/models/handpd_spiral_model_mobile_fixed.ptl
    - assets/models/finalNhats_fixed.ptl
    - assets/models/lifestyle.tflite
    - assets/models/finalADPDVoice.ptl

    - assets/labels.txt
    - assets/spiral_labels.txt
    - assets/spiral_template.png
    - assets/audio_labels.txt
    - assets/PDFace_labels.txt

    - assets/icon/apk_icon.png